<?php 
header('Content-type: text/html; charset=iso-8859-1');
?><html>
<head>
<title>Administration Help</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body style="font-family: Verdana; font-size: 10px" link="#000000" vlink="#000000" alink="#000000" bgcolor="#FFFFFF">
<center><big><b>Administration help</b></big></center><br>

<li><b>Index</b> : On this page you can see your administration, on the left a speed menu,
 on the right a speed under menu, notifications, actions, SQL errors, message of www.nuked-klan.org, and administrator discussions...</li><br>
<li><b>Notification</b> : This new system is able to inform you about an automatic action of your website, or to inform you if you received a contact mail or a suggest.</li><br>
<li><b>SQL Error</b> : This system allows you to see errors SQL generated by your website.</li><br>
<li><b>Discussion</b> : It's a chat between administrators an or other people of your staff.</li><br>
<li><b>Action</b> : This system is an history of actions done on the administration like delete, modification, or add operations.
<li><b>Message of nuked-klan.org</b> : This announc is a sent message by Nuked-Klan to notify users (ex : new version available)</li><br>
<br>
<br>
<br>
<br>
</body></html>
